[package]
name = "check_passwords"
author = "Travis Veazey <travis.veazey@k12northstar.org>"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
